### ISSUE TITLE
[BUG] Unable to download from bunkr or gofile

### ISSUE THREAD

**Issue by gajrajsa** [jbsparrow/CyberDropDownloader#1565]
### I have taken steps to troubleshoot my issue first

- [x] I'm using the latest version of `cyberdrop-dl-patched`
- [x] I’ve read the wiki and my issue isn’t already covered.
- [x] I understand this is open source software provided for free and that I might not receive a timely response.
- [x] I’ve checked existing issues to avoid creating a duplicate.
- [ ] A similar issue was previously marked as `completed` and the [changelog](https://github.com/jbsparrow/CyberDropDownloader/blob/dev/CHANGELOG.md) says it was implemented, but I'm confident the bug still exists
- [ ] I am willing to submit a pull request with the fix. *(Assign this issue to me.)*

### Describe the bug

I am using 8.8.0 version in Android. I have followes the installation steps as mentioned in wiki. I am unable to download from gofile or bunkr.

### Relevant logs

[downloader.log](https://github.com/user-attachments/files/24139124/downloader.log)

### Cyberdrop-DL version

8.8.0

**Comment by adventure4u-proton** [comment]
seeing this from every gofile link I've tried lately:
[12/17/25 16:41:29] ERROR    [GoFile] Unable to get website token. Crawler has been disabled
                    ERROR    Scrape Failed: https://api.gofile.io (404 Not Found)

I've tried exporting cookies for gofile, doesn't work.

**Comment by gajrajsa** [comment]
@adventure4u-proton is bunkr working fine for you? Which os you are using?

**Comment by adventure4u-proton** [comment]
> [@adventure4u-proton](https://github.com/adventure4u-proton) is bunkr working fine for you? Which os you are using?

Bunkr seems to be working fine but I will keep an eye out.  running on linux.

The gofile issue seems to have been fixed by today's update.

**Comment by gajrajsa** [comment]
yes gofile issue fixed for me as well but still facing bunkr issue

**Comment by gajrajsa** [comment]
@adventure4u-proton can you share which installation method you are using?

I am using `uv` to install and seems like some of the dependencies are missing when installing with this.

**Comment by NormanMises** [comment]
I have the same issue, bunkr 404 error

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File href="file:///D:/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List href="file:///D:/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">


url | error | referer | origin
-- | -- | -- | --
https://maple.bunkr.ru/928b1641-8d8c-41ac-9274-dc7dee4b5677.mp4?n=woohankyung_2025-12-13-highlights-pt1.mp4 | 404 Not Found | https://bunkr.site/f/DIiafx1j27Wve | https://bunkr.cr/a/55VXV4c7
https://maple.bunkr.ru/b6767c95-069a-42f1-b62e-b7835959f099.mp4?n=woohankyung_2025-12-13-highlights-pt2.mp4 | 404 Not Found | https://bunkr.site/f/vBRy6ceEchGSz | https://bunkr.cr/a/55VXV4c7
https://maple.bunkr.ru/fe89427f-bb49-444b-a536-31dde30cd355.mp4?n=yunyeson3015_2025-12-03(3).mp4 | 404 Not Found | https://bunkr.site/f/ldz8F03HlzL8B | https://bunkr.cr/a/3a3U1sWs
https://maple.bunkr.ru/a155fdb0-e741-40b7-9136-8a71e56b8edc.mp4?n=yunyeson3015_2025-12-03(1).mp4 | 404 Not Found | https://bunkr.site/f/ppB4c2NxNlPxe | https://bunkr.cr/a/3a3U1sWs
https://maple.bunkr.ru/6034aaef-1c3e-4dff-9898-6b3f5b317b61.mp4?n=yunyeson3015_2025-12-03(2).mp4 | 404 Not Found | https://bunkr.site/f/SB7RieyG7NB0J | https://bunkr.cr/a/3a3U1sWs
https://maple.bunkr.ru/dafecadd-e5db-4d52-ad62-641c3241293c.mp4?n=yunyeson3015_2025-12-02.mp4 | 404 Not Found | https://bunkr.site/f/yxZWMKxHnxwrl | https://bunkr.cr/a/3a3U1sWs
https://maple.bunkr.ru/e60b94df-6280-4662-8aa6-b741376a703c.mp4?n=yunyeson3015_2025-12-01.mp4 | 404 Not Found | https://bunkr.site/f/Avh48wQn1rBhD | https://bunkr.cr/a/3a3U1sWs
https://maple.bunkr.ru/dcc7c3a5-bae0-4395-bd45-93da00e860b6.mp4?n=yunyeson3015_2025-11-30.mp4 | 404 Not Found | https://bunkr.site/f/WmExrf7mhRbT4 | https://bunkr.cr/a/3a3U1sWs
https://maple.bunkr.ru/a19f58fc-0386-4e23-b0ab-6010a52956a3.mp4?n=yunyeson3015_2025-11-25.mp4 | 404 Not Found | https://bunkr.site/f/zfEnOJKFRuTIl | https://bunkr.cr/a/3a3U1sWs
https://maple.bunkr.ru/e254906c-9ee6-4f54-82df-f1d0788a4caf.mp4?n=aesoon_96_2025-02-03.mp4 | 404 Not Found | https://bunkr.site/f/9biYYLq5NUG5n | https://bunkr.cr/a/3a3U1sWs
https://maple.bunkr.ru/bc0ff905-0a64-471d-97a9-13df0e7a7ac3.mp4?n=yunyeson3015_2025-11-22.mp4 | 404 Not Found | https://bunkr.site/f/PeWoaynlwr246 | https://bunkr.cr/a/3a3U1sWs
https://maple.bunkr.ru/0ee405aa-1e31-4a0e-a491-ce4ceed40746.mp4?n=yunyeson3015_2025-11-21.mp4 | 404 Not Found | https://bunkr.site/f/fxb1jjYgA8UOP | https://bunkr.cr/a/3a3U1sWs
https://maple.bunkr.ru/077b414f-fba9-4c33-9414-f88cba459d65.mp4?n=yunyeson3015_2025-11-20(2).mp4 | 404 Not Found | https://bunkr.site/f/dJqouBxla0XlR | https://bunkr.cr/a/3a3U1sWs
https://maple.bunkr.ru/eaf64c66-76d3-4b62-8d47-4468fb2a98ec.mp4?n=yunyeson3015_2025-11-20(1).mp4 | 404 Not Found | https://bunkr.site/f/DnkpbYCYoXIfB | https://bunkr.cr/a/3a3U1sWs
https://maple.bunkr.ru/b4e9b442-7103-4d70-9a53-0b85b6ca9a9c.mp4?n=yunyeson3015_2025-11-08(1).mp4 | 404 Not Found | https://bunkr.site/f/d87yAHRRX2LMp | https://bunkr.cr/a/3a3U1sWs
https://maple.bunkr.ru/8d78ba79-063f-40dd-822f-6a6001fc38d9.mp4?n=yunyeson3015_2025-11-08(2).mp4 | 404 Not Found | https://bunkr.site/f/BZS5n7NQfwUYJ | https://bunkr.cr/a/3a3U1sWs
https://rice.bunkr.ru/afea2cbb-f59c-4ea0-8455-facb06a69894.mp4?n=woohankyung_2025-12-23-highlights.mp4 | Bunkr Maintenance | https://bunkr.site/f/kkEqXZFacbdyx | https://bunkr.cr/a/55VXV4c7
https://rice.bunkr.ru/8ebbe744-1fce-4b8f-9ed6-0e1a859c75e4.mp4?n=yunyeson3015_2025-12-24(2).mp4 | Bunkr Maintenance | https://bunkr.site/f/DqnAoZEfVgXUR | https://bunkr.cr/a/3a3U1sWs
https://rice.bunkr.ru/d40f4168-6f8b-43e1-9b11-a2e41ae7b71b.mp4?n=yunyeson3015_2025-12-24(1).mp4 | Bunkr Maintenance | https://bunkr.site/f/mrZCWUG8Sf9KB | https://bunkr.cr/a/3a3U1sWs
https://rice.bunkr.ru/dd95bac8-cafe-47e2-b547-5d3af86c55ea.mp4?n=yunyeson3015_2025-12-23.mp4 | Bunkr Maintenance | https://bunkr.site/f/56QBQd1wojciC | https://bunkr.cr/a/3a3U1sWs
https://rice.bunkr.ru/346fcffe-e140-4599-8aac-100f5718d80b.mp4?n=yunyeson3015_2025-12-17.mp4 | Bunkr Maintenance | https://bunkr.site/f/lY4UrnIN5joif | https://bunkr.cr/a/3a3U1sWs



</body>

</html>

**Comment by NTFSvolume** [comment]
The errors above are related to their maintenance. Wait for a few weeks until they are done
